
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB988B0"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.hints.end]
background = "#4C566A"
foreground = "#81A1C1"

[colors.hints.start]
background = "#4C566A"
foreground = "#B988B0"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB988B0"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x000000"
foreground = "0xC8D0E0"


[colors.search.focused_match]
background = "#4C566A"
foreground = "#EBCB8B"

[colors.search.matches]
background = "#4C566A"
foreground = "#81A1C1"

[colors.selection]
background = "#3F4758"
text = "CellForeground"

[font]
size = 11

[font.normal]
family = "DejaVu Sans Mono"

[font.offset]
x = 0

[window]
opacity = 0.8

[window.dimensions]
columns = 100
lines = 85

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
